### ISSUE TITLE
Please enhance this program to support position parameters

### ISSUE THREAD

**Issue by asdcmsic** [asdcmsic/test#10]
Positional Parameters are not taken care in this program. Please enhance this program to support position parameters
lego@Lego-OptiPlex-3020:~/Scripts$ ./pal.sh 333
Enter the number to check is it palindrome or not: 
Yes you are right 121 is palindrome
Do you want to continue[y/n]

ref : https://github.com/asdcmsic/test/pull/8

**Comment by IbneRaveem** [comment]
I am done with it
